# Generated by Django 3.1 on 2020-08-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200825_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
