# Generated by Django 3.1 on 2020-09-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_link_duration', models.DurationField(verbose_name='activation time')),
            ],
        ),
    ]
