# Generated by Django 3.1 on 2020-09-17 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_controlmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlmodel',
            name='activation_link_duration',
        ),
        migrations.AddField(
            model_name='controlmodel',
            name='link_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0, 60), verbose_name='activation time'),
        ),
        migrations.AddField(
            model_name='controlmodel',
            name='name',
            field=models.CharField(default='global timedelta', max_length=255, verbose_name='variable name'),
        ),
    ]
